#include "rtc.h"
#include "interrupt_handlers.h"
#include "i8259.h"
#include "lib.h"
#include "x86_desc.h"

int int_occur = 0;

/*
 * rtc_handler(void)
 *
 * DESCRIPTION: Processes interrupts generated by the RTC
 *
 * INPUTS: 	none
 * OUTPUTS: none
 *
 * SIDE EFFECTS: N/A
 *
 */
void rtc_handler() {
    cli();

    int_occur = 1;

    // Throw away contents
    outb(RTC_REG_C, RTC_PORT);
    inb(CMOS_PORT);

    // Send eoi to PIC
    send_eoi(RTC_IRQ_LINE);
    sti();
}
/*
 * rtc_open(void)
 *
 * DESCRIPTION: Opens file
 *
 * INPUTS:  none
 * OUTPUTS: none
 *
 * SIDE EFFECTS: opens file
 *
 */
int32_t rtc_open(const int8_t *filename)
{
    cli();
    // Turn RTC on
    outb(RTC_REG_B, RTC_PORT);
    char prev = inb(CMOS_PORT);
    outb(RTC_REG_B, RTC_PORT);
    outb(prev | RTC_ENABLE_INTERRUPT, CMOS_PORT);

    // Set rate to 0
    outb(RTC_REG_A, RTC_PORT);
    prev = inb(CMOS_PORT);
    outb(RTC_REG_A, RTC_PORT);
    outb((prev & RTC_SET_RATE) | 15, CMOS_PORT);

    int_occur = 0;

    // Enable interrupts
    enable_irq(RTC_IRQ_LINE);
    sti();

    return 0;
}

/*
 * rtc_close(void)
 *
 * DESCRIPTION: Closes file
 *
 * INPUTS:  none
 * OUTPUTS: none
 *
 * SIDE EFFECTS: closes file
 *
 */
int32_t rtc_close(int32_t fd)
{
    // Stop interrupts on close
    disable_irq(RTC_IRQ_LINE);

    // Set rate to 0
    outb(RTC_REG_A, RTC_PORT);
    char prev = inb(CMOS_PORT);
    outb(RTC_REG_A, RTC_PORT);
    outb((prev & RTC_SET_RATE) | 0, CMOS_PORT);

    return 0;
}
/*
 * rtc_read(buf, nbytes)
 *
 * DESCRIPTION: reads rtc after interupt
 *
 * INPUTS:  buf - pointer to buffer
            nbytes - number of bytes being read
 * OUTPUTS: none
 *
 * SIDE EFFECTS: N/A
 *
 */
int32_t rtc_read(int32_t fd, void *buf, int32_t nbytes)
{
    while(!int_occur)
    {
        //spins
    }
    int_occur = 0;
    return 0;
}
/*
 * rtc_read(buf, nbytes)
 *
 * DESCRIPTION: writes frequency of rtc
 *
 * INPUTS:  buf - pointer to buffer
            nbytes - number of bytes being read
 * OUTPUTS: none
 *
 * SIDE EFFECTS: changes frequency
 *
 */
int32_t rtc_write(int32_t fd, const void *buf, int32_t nbytes)
{
    cli();
    if (buf == NULL || nbytes < 4) {
        sti();
        return -1;
    }

    int32_t freq = *(int32_t *)buf;
    char rate = freq == 0 ? 0 : 16;
    while (freq > 1) {
        rate--;
        freq >>= 1;
    }

    outb(RTC_REG_A, RTC_PORT);
    char prev = inb(CMOS_PORT);
    outb(RTC_REG_A, RTC_PORT);
    outb((prev & RTC_SET_RATE) | rate, CMOS_PORT);
    sti();

    return 0;
}
